// PRODUCT_CATEGORY
export const GET_PRODUCT_CATEGORYS = "GET_PRODUCT_CATEGORYS";

export const GET_ALL_PRODUCT_CATEGORYS = "GET_ALL_PRODUCT_CATEGORYS";

export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";

export const ADD_PRODUCT_CATEGORY = "ADD_PRODUCT_CATEGORY";

export const GET_SINGLE_PRODUCT_CATEGORY = "GET_SINGLE_PRODUCT_CATEGORY";

export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";

// PRODUCT_SUB_CATEGORY
export const GET_PRODUCT_SUB_CATEGORYS = "GET_PRODUCT_SUB_CATEGORYS";

export const GET_ALL_PRODUCT_SUB_CATEGORYS = "GET_ALL_PRODUCT_SUB_CATEGORYS";

export const DELETE_PRODUCT_SUB_CATEGORY = "DELETE_PRODUCT_SUB_CATEGORY";

export const ADD_PRODUCT_SUB_CATEGORY = "ADD_PRODUCT_SUB_CATEGORY";

export const GET_SINGLE_PRODUCT_SUB_CATEGORY = "GET_SINGLE_PRODUCT_SUB_CATEGORY";

export const UPDATE_PRODUCT_SUB_CATEGORY = "UPDATE_PRODUCT_SUB_CATEGORY";

// PRODUCT_BRAND
export const GET_PRODUCT_BRANDS = "GET_PRODUCT_BRANDS";

export const GET_ALL_PRODUCT_BRANDS = "GET_ALL_PRODUCT_BRANDS";

export const DELETE_PRODUCT_BRAND = "DELETE_PRODUCT_BRAND";

export const ADD_PRODUCT_BRAND = "ADD_PRODUCT_BRAND";

export const GET_SINGLE_PRODUCT_BRAND = "GET_SINGLE_PRODUCT_BRAND";

export const UPDATE_PRODUCT_BRAND = "UPDATE_PRODUCT_BRAND";

// PRODUCT_ATTRIBUTE
export const GET_PRODUCT_ATTRIBUTES = "GET_PRODUCT_ATTRIBUTES";

export const GET_ALL_PRODUCT_ATTRIBUTES = "GET_ALL_PRODUCT_ATTRIBUTES";

export const DELETE_PRODUCT_ATTRIBUTE = "DELETE_PRODUCT_ATTRIBUTE";

export const ADD_PRODUCT_ATTRIBUTE = "ADD_PRODUCT_ATTRIBUTE";

export const GET_SINGLE_PRODUCT_ATTRIBUTE = "GET_SINGLE_PRODUCT_ATTRIBUTE";

export const UPDATE_PRODUCT_ATTRIBUTE = "UPDATE_PRODUCT_ATTRIBUTE";

// PRODUCT
export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";

export const GET_PRODUCTS_BY_SUBCATEGORY = "GET_PRODUCTS_BY_SUBCATEGORY";

export const GET_PRODUCTS_BY_BRAND = "GET_PRODUCTS_BY_BRAND";

export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";

export const GET_NEW_ARRIVAL_PRODUCTS = "GET_NEW_ARRIVAL_PRODUCTS";

export const GET_SIMILAR_PRODUCTS = "GET_SIMILAR_PRODUCTS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_PRODUCT = "ADD_PRODUCT";

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";


// USER
export const GET_USERS = "GET_USERS";

export const DELETE_USER = "DELETE_USER";

export const ADD_USER = "ADD_USER";

export const GET_SINGLE_USER = "GET_SINGLE_USER";

export const UPDATE_USER = "UPDATE_USER";

// PAYMENT
export const GET_PAYMENTS = "GET_PAYMENTS";

export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";

export const GET_SINGLE_PAYMENT = "GET_SINGLE_PAYMENT";

export const UPDATE_PAYMENT = "UPDATE_PAYMENT";

// COUPON
export const GET_COUPONS = "GET_COUPONS";

export const GET_ALL_COUPONS = "GET_ALL_COUPONS";

export const DELETE_COUPON = "DELETE_COUPON";

export const ADD_COUPON = "ADD_COUPON";

export const GET_SINGLE_COUPON = "GET_SINGLE_COUPON";

export const UPDATE_COUPON = "UPDATE_COUPON";

// SITE_SETTING
export const GET_SITE_SETTINGS = "GET_SITE_SETTINGS";

export const UPDATE_SITE_SETTING = "UPDATE_SITE_SETTING";

// Custom ABOUT_PAGE
export const GET_ABOUT_PAGE = "GET_ABOUT_PAGE";

export const UPDATE_ABOUT_PAGE = "UPDATE_ABOUT_PAGE";

// Custom PRIVACY_PAGE
export const GET_PRIVACY_PAGE = "GET_PRIVACY_PAGE";

export const UPDATE_PRIVACY_PAGE = "UPDATE_PRIVACY_PAGE";

// Custom REFUND_PAGE
export const GET_REFUND_PAGE = "GET_REFUND_PAGE";

export const UPDATE_REFUND_PAGE = "UPDATE_REFUND_PAGE";

// Custom TERMS_PAGE
export const GET_TERMS_PAGE = "GET_TERMS_PAGE";

export const UPDATE_TERMS_PAGE = "UPDATE_TERMS_PAGE";

// SLIDER
export const GET_SLIDERS = "GET_SLIDERS";

export const GET_ALL_SLIDERS = "GET_ALL_SLIDERS";

export const DELETE_SLIDER = "DELETE_SLIDER";

export const ADD_SLIDER = "ADD_SLIDER";

export const GET_SINGLE_SLIDER = "GET_SINGLE_SLIDER";

export const UPDATE_SLIDER = "UPDATE_SLIDER";

// HELP
export const GET_HELPS = "GET_HELPS";

export const DELETE_HELP = "DELETE_HELP";

export const ADD_HELP = "ADD_HELP";

export const GET_SINGLE_HELP = "GET_SINGLE_HELP";

export const UPDATE_HELP = "UPDATE_HELP";


// FAQ
export const GET_FAQS = "GET_FAQS";

export const GET_ALL_FAQS = "GET_ALL_FAQS";

export const DELETE_FAQ = "DELETE_FAQ";

export const ADD_FAQ = "ADD_FAQ";

export const GET_SINGLE_FAQ = "GET_SINGLE_FAQ";

export const UPDATE_FAQ = "UPDATE_FAQ";


// 🤵 user's constant

// PROFILE BY_ID
export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";

export const UPDATE_PROFILE_BY_ID = "UPDATE_PROFILE_BY_ID";


// USER ADDRESS
export const GET_USER_ADDRESSS = "GET_USER_ADDRESSS";

export const GET_USER_ADDRESSS_BY_USER_ID = "GET_USER_ADDRESSS_BY_USER_ID";

export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";

export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";

export const GET_SINGLE_USER_ADDRESS = "GET_SINGLE_USER_ADDRESS";

export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";

// ADD TO CART 
export const GET_FROM_CART = "GET_FROM_CART";

export const ADD_TO_CART = "ADD_TO_CART";

export const CHECK_ALREADY_ADD = "CHECK_ALREADY_ADD";

export const UNIQUE_ITEM_QUANTITY = "UNIQUE_ITEM_QUANTITY";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const EMPTY_CART = "EMPTY_CART";

// Add To Wishlist
export const GET_WISHLIST_BY_USERID = "GET_WISHLIST_BY_USERID";

// Product Order
export const GET_ORDERS = "GET_ORDERS";

export const GET_ORDERS_BY_USER_ID = "GET_ORDER_BY_USER_ID";

export const ADD_ORDER = "ADD_ORDER";

export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER";

export const UPDATE_ORDER = "UPDATE_ORDER";



// Product Reviews
export const ADD_REVIEW = "ADD_REVIEW";

export const GET_REVIEWS_BY_PRODUCT_ID = "GET_REVIEWS_BY_PRODUCT_ID";

// SEARCH PRODUCT
export const GET_SEARCHED_PRODUCTS = "GET_SEARCHED_PRODUCTS";

// Get Cancellation Reasons
export const GET_CANCELLATION_REASONS = "GET_CANCELLATION_REASONS";

// Get Return Reasons
export const GET_RETURN_REASONS = "GET_RETURN_REASONS";

// Get SIngle Return Reasons
export const GET_SINGLE_RETURN_REASONS = "GET_SINGLE_RETURN_REASONS";

// Get Return Sub Reasons
export const GET_RETURN_SUB_REASONS = "GET_RETURN_SUB_REASONS";

// Get Return Sub Reasons bu return id
export const GET_RETURN_SUB_REASONS_BY_ID = "GET_RETURN_SUB_REASONS_BY_ID";

// Get Order Status
export const GET_ORDER_STATUS = "GET_ORDER_STATUS";

// Get Order Status Logs
export const GET_ORDER_STATUS_LOGS = "GET_ORDER_STATUS_LOGS";

// Get return request
export const GET_RETURN_REQUESTS = "GET_RETURN_REQUESTS";

// Get single return request
export const GET_SINGLE_RETURN_REQUESTS = "GET_SINGLE_RETURN_REQUESTS";

// Get Statistics
export const GET_STATISTICS = "GET_STATISTICS";
